import type { DocumentChunk } from '../knowledge/models/document-chunk.js';

/**
 * Represents the vector generated for a document chunk.
 *
 * The embedding is intentionally separated from the DocumentChunk so the same
 * chunk can have embeddings generated by different providers or models.
 */
export interface EmbeddedChunk {
  /**
   * Original chunk.
   */
  chunk: DocumentChunk;

  /**
   * Name of the embedding provider.
   *
   * Example:
   *  - openai
   *  - voyage
   *  - jina
   */
  provider: string;

  /**
   * Embedding model name.
   *
   * Example:
   *  - text-embedding-3-small
   *  - voyage-3
   */
  model: string;

  /**
   * Dense embedding vector.
   */
  embedding: readonly number[];
}
